### ISSUE TITLE
MrPeak技术分享

### ISSUE THREAD

**Issue by music4kid** [pockry/mobile-frontier#27]
姓名：MrPeak
关注领域：iOS, Android
博客：mrpeak.cn
GitHub: music4kid
公众号：MrPeakTech

**Comment by pockry** [comment]
Hi, 你是否还没有加入我们的分享群？

**Comment by music4kid** [comment]
什么分享群呢？

**Comment by pockry** [comment]
是移动前线的分享群，加入方法在文档里有写 :)
