### ISSUE TITLE
提交信息

### ISSUE THREAD

**Issue by ChrisZou** [pockry/mobile-frontier#9]
姓名：小创
关注领域：Android、Kotlin、React、Ruby、Ruby on Rails、Elixir
博客：[小创](http://chriszou.com/)
公众号：小创作
![qrcode_for_gh_0e0f738a1213_430 4](https://cloud.githubusercontent.com/assets/3190416/13623298/869512c4-e5e0-11e5-985c-7428cec7dbfa.jpg)

**Comment by pockry** [comment]
你这个博客，我看了第一页，没有和移动相关的啊

**Comment by ChrisZou** [comment]
@pockry 有的啊，后面的Robolectric和Otto都是安卓的

**Comment by pockry** [comment]
好吧，感谢支持哈，我先收录进去，建议你缩小关注范围，这样别人看起来不会迷惑。:)

**Comment by ChrisZou** [comment]
@pockry 好的，谢谢！
